### ISSUE TITLE
question: Write go to Master origin ?

### ISSUE THREAD

**Issue by gedw99** [benbjohnson/litestream-read-replica-example#1]
hey @benbjohnson 

I need to set this up with Pocketable, and wanted to know the sure fire way to do this on a globally replicated fly setup.

Does this fly config make it so that writes go to Master ( origin DC as some would call it ), and reads go to Secondaries ?

Because of the Anycast fly system, a user will go to nearest DC, so on a http  write, its hitting the Secondary DC ( closest to Usr ) and then under the hood the DB write is hitting Master DC Sqlite DB ?

**Comment by gedw99** [comment]
Also if there is a better example, please let me know, as this looks a bit old :)

**Comment by benbjohnson** [comment]
@gedw99 The read replication was removed from Litestream because it was untenable. Replication was implemented in [LiteFS](https://fly.io/docs/litefs/) instead.

**Comment by benbjohnson** [comment]
I'll mark this repo as archived.
